#!/usr/bin/env python

import sys
from os.path import abspath, join, dirname, pardir
import time

# sys.path.insert(0, abspath(join(dirname(__file__), pardir, "build", "packages", "python")))
sys.path.insert(0, abspath(join(dirname(__file__), pardir, "lib")))

from retest.framework import run, Test, TestTree, SimpleTest
from retest.unit import AllUnitTests

def pass_():
    pass

def fail():
    raise Exception("failed")

def wait(n):
    return lambda: time.sleep(n)

tests = TestTree({
    'dummy': TestTree({
        'pass': SimpleTest(pass_),
        'fail': SimpleTest(fail),
        'timeout': SimpleTest(wait(2), timeout=1),
        'notimeout': SimpleTest(wait(2)),
        'print': SimpleTest(lambda: sys.stdout.write('hello\n'))
    }),
    'unit': AllUnitTests()
})

if __name__ == '__main__':
    run(tests, sys.argv[1:])
