#!/usr/bin/env python

import sys
import os
from os.path import abspath, join, dirname, pardir
import time
import argparse

sys.path.insert(0, abspath(join(dirname(__file__), "common")))

from test_framework import run, Test, TestTree, SimpleTest, group_from_file
import test_framework
from unit import AllUnitTests
from shelltest import ShellCommandTest

# Initialise the list of tests with the dumy tests and the unit tests
tests = TestTree({
    'unit': AllUnitTests()
})

# helper function for loading tests from full_test/*.test
def generate_test(tree):
    def gen(test_command, name):
        i = 1
        new_name = name
        while tree.has_test(new_name):
            i = i + 1
            new_name = name + '-' + str(i)
        tree[new_name] = ShellCommandTest(test_command)
    return gen

# load the tests from full_test/*.test
def load_tests():
    dirpath = join(dirname(__file__), "full_test")
    for filename in os.listdir(dirpath):
        parts = filename.split('.')
        if parts[-1] == 'test':
            if len(parts) > 2:
                raise Exception("Filename contains to many `.': %s" % (filename,))
            base_name = parts[0]
            tree = TestTree();
            full_path = os.path.join(dirpath, filename)
            execfile(full_path, {"__builtins__": __builtins__, "generate_test": generate_test(tree)})
            tests.add(base_name, tree)

# Test groups
groups = {}

# Load the test groups from full_test/*.group
def load_groups():
    for (dirpath, __, filenames) in os.walk(join(dirname(__file__), "full_test")):
        filenames = [f for f in filenames if f.split('.')[-1] == 'group']
        for filename in filenames:
            base_name = filename.split('.')[0]
            full_path = os.path.join(dirpath, filename)
            groups[base_name] = group_from_file(full_path)

argparser = argparse.ArgumentParser(parents=[test_framework.argparser])
argparser.add_argument('-b', '--build-dir', default=None,
                       help='The rethinkdb build directory (Default: the latest one)')
argparser.add_argument('-M', '--make', default=False, action='store_true',
                       help='Build missing dependencies')


if __name__ == '__main__':
    args = argparser.parse_args(sys.argv[1:])
    load_tests()
    load_groups()
    run(tests, groups, args)
